title: TEDxWarwick IPA Repository
permalink: /:title


#############
# Renderers #
#############

markdown: kramdown

kramdown:
  auto_ids: false
  parse_block_html: true

sass:
  style: compressed

plugins:
  - jekyll-redirect-from

error_mode: strict
strict_variables: true
strict_filters: true


#########
# Files #
#########

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
  - LICENSE
  - README.md
  - CNAME


###################
# Site parameters #
###################

url: https://ipa.tedxw.co

repo: "TEDxWarwickTechnical/ipa"
